input {
  file {
    path => "/usr/share/logstash/logs/sample.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => { "message" => "%{COMBINEDAPACHELOG}" }
  }
  date {
    match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
  }
  mutate {
    add_field => { "environment" => "fintech-lab" }
    add_field => { "app" => "payment-api" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "fintech-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
