input {
  file {
    path => "/usr/share/logstash/logs/sample.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    tags => ["fintech", "payment-api", "web"]
  }
}

filter {
  grok {
    match => {
      "message" => "%{COMBINEDAPACHELOG}"
    }
    add_tag => ["grok_success"]
    tag_on_failure => ["grok_failure"]
  }

  
  if "grok_failure" in [tags] {
    mutate {
      add_field => { "parse_error" => "true" }
    }
  }

  
  date {
    match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
    target => "@timestamp"
  }

  
  mutate {
    convert => {
      "response" => "integer"
      "bytes" => "integer"
    }
  }

  mutate {
    add_field => {
      "environment" => "fintech-lab"
      "app" => "payment-api"
      "datacenter" => "lagos-dc1"
    }
  }

  #Flag suspicious activity based on HTTP response codes
  if [response] == 401 {
    mutate {
      add_tag => ["unauthorized_access"]
      add_field => { "alert_level" => "medium" }
    }
  }

  if [response] == 403 {
    mutate {
      add_tag => ["forbidden_access"]
      add_field => { "alert_level" => "medium" }
    }
  }

  if [response] >= 500 {
    mutate {
      add_tag => ["server_error"]
      add_field => { "alert_level" => "high" }
    }
  }

  
  if [response] == 401 {
    mutate {
      add_tag => ["potential_brute_force"]
    }
  }

  mutate {
    remove_field => ["message", "timestamp", "host"]
  }
}

output {
  
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "fintech-logs-%{+YYYY.MM.dd}"
  }

  
  stdout {
    codec => rubydebug
  }
}

